import json
import re

# JSON 파일 로드
with open('backend/scripts/food-rules-data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

sql_statements = []

# 영양소 파싱 함수
def parse_nutrient(value_str):
    if not value_str: return 0
    # "120kcal", "1.5g", "10mg" 등에서 숫자만 추출
    match = re.search(r'([\d\.]+)', str(value_str))
    if match:
        return float(match.group(1))
    return 0

for food_name, info in data.items():
    warnings = []
    tips = []
    
    nutrients = info.get('nutrients', {})
    disease_analysis = info.get('diseaseAnalysis', {})
    
    # 1. 영양소 기반 분석
    sodium = parse_nutrient(nutrients.get('sodium', '0'))
    sugar = parse_nutrient(nutrients.get('sugar', '0'))
    fat = parse_nutrient(nutrients.get('fat', '0'))
    protein = parse_nutrient(nutrients.get('protein', '0'))
    potassium = parse_nutrient(nutrients.get('potassium', '0'))
    calories = parse_nutrient(nutrients.get('calories', '0'))
    
    # 나트륨 경고
    if sodium >= 800:
        warnings.append(f"매우 높은 나트륨 함량({sodium}mg) - 고혈압/신장질환 주의")
        tips.append("국물 섭취를 자제하고 건더기 위주로 드세요")
        tips.append("칼륨이 풍부한 채소(토마토, 바나나 등)와 함께 드시면 나트륨 배출에 도움이 됩니다")
    elif sodium >= 400:
        warnings.append(f"높은 나트륨 함량({sodium}mg) 주의")
        tips.append("조리 시 소금이나 간장 사용을 줄이고 천연 향신료를 활용하세요")

    # 당류 경고
    if sugar >= 20:
        warnings.append(f"매우 높은 당류 함량({sugar}g) - 혈당 급상승 주의")
        tips.append("섭취량을 절반으로 줄이거나, 식사 후 디저트로 소량만 드세요")
    elif sugar >= 10:
        warnings.append(f"당류 함량({sugar}g) 주의")
        tips.append("과다 섭취 시 체중 증가의 원인이 될 수 있습니다")

    # 지방/포화지방 팁
    if fat >= 15:
        warnings.append(f"높은 지방 함량({fat}g) - 고지혈증 주의")
        tips.append("기름기를 제거하거나 튀기는 대신 굽거나 찌는 조리법을 선택하세요")
        
    # 칼륨 팁 (신장질환 관련)
    if potassium >= 500:
        warnings.append(f"고칼륨 식품({potassium}mg) - 신장질환자 섭취 제한 필요")
        tips.append("신장 기능이 저하된 경우, 물에 2시간 이상 담가 칼륨을 뺀 후 조리하세요")
        tips.append("채소는 데쳐서 드시면 칼륨 함량을 줄일 수 있습니다")

    # 단백질 팁
    if protein >= 15:
        tips.append(f"훌륭한 단백질 공급원({protein}g)입니다")
        tips.append("근육 유지와 면역력 강화에 도움이 됩니다")

    # 2. 질병 분석 기반 경고 (Risk: warning/caution)
    for disease, analysis in disease_analysis.items():
        risk = analysis.get('risk')
        reason = analysis.get('reason')
        if risk == 'warning':
            warnings.append(f"🚨 {disease} 위험: {reason}")
        elif risk == 'caution':
            warnings.append(f"⚠️ {disease} 주의: {reason}")

    # 3. 전문가 조언 (Expert Advice) 활용
    expert_advice = info.get('expertAdvice')
    if expert_advice:
        tips.append(f"💡 전문가 조언: {expert_advice}")

    # 4. 장단점(Pros/Cons) 활용
    cons = info.get('cons')
    if cons:
        # 단점 텍스트를 분리해서 경고에 추가 (너무 길면 생략)
        cons_list = [c.strip() for c in cons.split(',')]
        for c in cons_list:
            if "주의" in c or "위험" in c or "부작용" in c:
                warnings.append(c)

    # 중복 제거 및 정리
    warnings = list(dict.fromkeys(warnings)) # 순서 유지 중복 제거
    tips = list(dict.fromkeys(tips))
    
    # SQL 생성 (배열 포맷팅)
    # 작은따옴표 이스케이프 처리
    warnings_sql = [w.replace("'", "''") for w in warnings]
    tips_sql = [t.replace("'", "''") for t in tips]
    
    warnings_str = ", ".join([f"'{w}'" for w in warnings_sql])
    tips_str = ", ".join([f"'{t}'" for t in tips_sql])
    
    sql = f"UPDATE food_rules SET warnings = ARRAY[{warnings_str}]::text[], cooking_tips = ARRAY[{tips_str}]::text[] WHERE food_name = '{food_name}';"
    sql_statements.append(sql)

# 파일 저장
with open('backend/migrations/20251217_enhanced_food_rules_update.sql', 'w', encoding='utf-8') as f:
    f.write("-- ========================================\n")
    f.write("-- food_rules 데이터 정밀 업데이트 (영양성분 및 질병분석 기반)\n")
    f.write("-- Generated by VS Code Assistant (Enhanced Logic)\n")
    f.write("-- ========================================\n\n")
    for stmt in sql_statements:
        f.write(stmt + "\n")

print(f"Generated {len(sql_statements)} enhanced SQL statements.")
